# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 196a7d7267b1afc1b6d17c1743e566630fdb9b81e8e6034396b8acef4a9b8500b0bb248e3143ce8b68c704eb3d89dd5fa498a90507e7de0dd68bcb8a92cc6c60

test:
  secret_key_base: 33d1a80dedec3840f944ec507f6637072d1f9fc811a09e7719b8ecd88d788040543a267c076b329a316b89f681e92af8e84785cb30ea0567897e68bb5d974610

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
